### ISSUE TITLE
Tìm hiểu về thuật toán A*

### ISSUE THREAD

**Issue by BToopS2** [BToopS2/AI-Snake_Project#1]

**Comment by BToopS2** [comment]
https://vi.wikipedia.org/wiki/Gi%E1%BA%A3i_thu%E1%BA%ADt_t%C3%ACm_ki%E1%BA%BFm_A*#:~:text=Thu%E1%BA%ADt%20to%C3%A1n%20A*%20%C4%91%C6%B0%E1%BB%A3c%20m%C3%B4,%C4%91%C3%B3%20m%C3%A0%20c%C3%B3%20t%C3%AAn%20A*.

**Comment by kiennehh** [comment]
Thuật toán A* (A star) là một thuật toán tìm kiếm đường đi ngắn nhất trên đồ thị, được sử dụng rộng rãi trong các ứng dụng trí tuệ nhân tạo và robot học.

Thuật toán A* sử dụng hai hàm để đánh giá mỗi nút trên đồ thị: hàm chi phí (g) và hàm ước lượng khoảng cách (h). Hàm chi phí tính toán chi phí của đường đi từ nút gốc đến nút hiện tại, trong khi hàm ước lượng khoảng cách ước tính khoảng cách từ nút hiện tại đến đích.

Thuật toán A* tìm kiếm đường đi bằng cách tìm kiếm nút có giá trị nhỏ nhất của hàm f = g + h. Thuật toán sẽ di chuyển đến các nút lá gần đích và sau đó truy vết ngược lại để tìm đường đi ngắn nhất.

Một ưu điểm của thuật toán A* là tìm kiếm đường đi ngắn nhất mà không phải tìm kiếm toàn bộ đồ thị, giảm thiểu thời gian tính toán. Tuy nhiên, nếu hàm ước lượng khoảng cách không được thiết lập đúng cách, thuật toán có thể không tìm được đường đi tối ưu.

Thuật toán A* có nhiều ứng dụng trong thực tế, bao gồm điều khiển robot, lập kế hoạch trong trò chơi và điều khiển máy móc tự động.
