### ISSUE TITLE
Thuật toán CNN là gì? Cấu trúc mạng Convolutional Neural Network !?

### ISSUE THREAD

**Issue by BToopS2** [BToopS2/AI-Snake_Project#2]

**Comment by BToopS2** [comment]
https://topdev.vn/blog/thuat-toan-cnn-convolutional-neural-network/

**Comment by kiennehh** [comment]
Thuật toán CNN (Convolutional Neural Network) là một loại thuật toán học sâu trong lĩnh vực thị giác máy tính và xử lý hình ảnh. Nó được sử dụng để phân loại và nhận dạng các hình ảnh và đối tượng trong đó.

Cấu trúc mạng CNN bao gồm các lớp tích chập (Convolutional layers), lớp gộp (Pooling layers), lớp kết nối đầy đủ (Fully Connected layers), và các lớp kích hoạt (Activation layers).

Các lớp tích chập được sử dụng để trích xuất các đặc trưng từ hình ảnh bằng cách áp dụng các bộ lọc trên toàn bộ hình ảnh. Các lớp gộp được sử dụng để giảm kích thước của đầu vào và làm giảm độ phức tạp của mô hình. Các lớp kết nối đầy đủ được sử dụng để phân loại hình ảnh đầu vào dựa trên các đặc trưng được trích xuất từ các lớp tích chập và gộp trước đó. Các lớp kích hoạt được sử dụng để kích hoạt các đơn vị tính toán trên các lớp trước đó.

Cấu trúc mạng CNN có thể được tùy chỉnh để phù hợp với nhiều loại bài toán trong xử lý hình ảnh, bao gồm nhận dạng khuôn mặt, phân loại đối tượng, phát hiện đối tượng, và nhiều bài toán khác. Nhờ vào khả năng trích xuất đặc trưng tự động từ hình ảnh và khả năng học tập, mạng CNN đã đạt được nhiều thành công đáng kể trong các ứng dụng thực tế như nhận dạng khuôn mặt, xe tự lái, và tìm kiếm hình ảnh trên mạng.
