### ISSUE TITLE
Các thuật toán phổ biến trong AI

### ISSUE THREAD

**Issue by BToopS2** [BToopS2/AI-Snake_Project#3]
https://viettelidc.com.vn/tin-tuc/cam-nang-ai-cac-thuat-toan-tim-kiem-pho-bien-trong-ai

**Comment by kiennehh** [comment]
1.Học máy (Machine Learning - ML)
2.Tìm kiếm và tối ưu (Search and Optimization)
3.Phân loại và phân cụm (Classification and Clustering)
4.Xử lý ngôn ngữ tự nhiên (Natural Language Processing - NLP)
5.Học tăng cường (Reinforcement Learning)

**Comment by BinhHuong** [comment]
https://labs.flinters.vn/algorithm/algorithm-cac-thuat-toan-tim-kiem-trong-ai/
