### ISSUE TITLE
Thuật toán áp dụng trong project of team là gì?

### ISSUE THREAD

**Issue by BToopS2** [BToopS2/AI-Snake_Project#5]

**Comment by NguyenTrieuVuong** [comment]
Có 2 chế độ rắn tự động ăn mồi: Single AI và A* AI. Trong đó A* AI sử dụng thuật toán Priority Queue nhằm tối ưu hoá đường đi khả dĩ của con rắn sao cho rắn đi tự động hiệu quả hơn so với Single AI.

**Comment by BToopS2** [comment]
like.
