### ISSUE TITLE
Mn cùng đưa ra Ý tưởng của project ?

### ISSUE THREAD

**Issue by BToopS2** [BToopS2/AI-Snake_Project#9]

**Comment by NguyenTrieuVuong** [comment]
Dùng A* tạo game rắn tự động. Con rắn được bao quanh bởi 4 bức tường, mồi mới xuất hiện ngẫu nhiên 1 vị trí sau khi rắn ăn mồi cũ. Trò chơi kết thúc khi rắn đâm vào bức tường hoặc đâm vào thân/đuôi chính nó.
